export { default as Home } from './Home'
export { default as Catalog } from './Catalog'
export { default as ProductPage } from './ProductPage'
export { default as Cart } from './Cart'
export { default as Wishlist } from './Wishlist'
export { default as Search } from './Search'